version: '3.1'

services:
  nginx-lb:
    image: nginx:alpine
    volumes: 
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - frontend

  web-server1:
    image: trafex/alpine-nginx-php7
    command: php -S 0.0.0.0:80 /var/www/html/index.php
    volumes: 
      - ./configs/index.php:/var/www/html/index.php
      - ./php.ini:/etc/php7/php.ini
    ports: 
      - "80"
    networks:
      - frontend
      - backend

  web-server2:
    image: trafex/alpine-nginx-php7
    command: php -S 0.0.0.0:80 /var/www/html/index.php
    volumes: 
      - ./configs/index.php:/var/www/html/index.php
      - ./php.ini:/etc/php7/php.ini
    ports: 
      - "80"
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306"
    environment:
      MYSQL_USER: 'mustelaris'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'consultas'
      MYSQL_ROOT_PASSWORD: '12345678' 
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
